update sdk
sdk/component/audio version: 9ece611
1. [common][wlan] modify the usage of wifi_get_tsf() due to new return value
sdk/loong version: a30dab0e7f
1. [common][usb] fix cdc acm other speed cfg desc issue
2. [common][floader] fixed fl debug log messed up
3. [usb][common] fix dplus uac example build err
4. [common][usb] tune readme for hid example
5. [common][kconfig] generate .config_default after menuconfig
6. [common][example] update socket_tcp_multithread readme
7. [AmebaDplus][wlan][halrf][bug fix-normal] bug fix for commit change the blutooth power limits.
8. [common][pmc] update pmc code for dslp
9. [common][bt] revise V3 patch download flow to support opcode is 2
10. [common][vfs] revoke error commit
11. [common][file_system] optimize Kconfig & CMakeList
12. [common][wlan] add wifi error code RTK_ERR_POWEROFF
13. [7005][wlan] add wifi hal speaker
14. [amebasmart][bt][le audio]  fix csip and aics auto test bug
15. [common][wlan] wifi api doc part13
16. [common][wlan]Optimize for API ipc deadlock issue part6.
17. [amebax][wlan] Add wifi radar part24.
18. [common][wlan] fix compile error for wifi_make
19. [amebasmart][build] Fix image process error
20. [common][os] remove direct cmd execute in xTimerGenericCommand
21. [common][wlan:example] update readme for example_wifi_enterprise
22. [common][soc] sync timer api of all ic
tools/ameba version: 4dafcfc
1. [tools][TraceTool] update TraceTool to v2.1.34
tools/image_scripts version: 4dcfcd2
tools/meta_tools version: a76a86b
1. [common] astyle check ignore link file
2. [common] support project clean and menuconfig clean
tools version: feff4ab
1. [common][wlan] Update Gravitation.exe binary

diff --git a/tools/meta_tools/git_hooks/pre-commit b/tools/meta_tools/git_hooks/pre-commit
--- a/tools/meta_tools/git_hooks/pre-commit
+++ b/tools/meta_tools/git_hooks/pre-commit
@@ -214,15 +214,23 @@ elif [ "$repo_name" != "audio" ]; then
 fi
 
 if [ -n "$changed_files" ]; then
-	echo
-	echo 'Indent changed files: '
+	filtered_files=()
 	for f in $changed_files
 	do
-		echo $f
+		if [ -L "$f" ]; then 
+			#ignore link file
+			continue
+		fi
+		filtered_files+=("$f")
 	done
-	# Only for AStyle 3.1
-	astyle --style=linux -p -xg -H -U -k3 -j -xC160 -xL -T4 -z2 -n -q $changed_files
-	git add $changed_files
+	if [ -n "$filtered_files" ]; then
+		echo
+		echo 'Indent changed files: '
+		echo "${filtered_files[@]}"
+		# Only for AStyle 3.1
+		astyle --style=linux -p -xg -H -U -k3 -j -xC160 -xL -T4 -z2 -n -q "${filtered_files[@]}"
+		git add "${filtered_files[@]}"
+	fi
 fi
 
 # Special indent for BT files
@@ -238,16 +246,27 @@ if [ "$repo_name" = "loong" ]; then
 		cut -d'	' -f 2)
 
 	if [ -n "$check_files" ]; then
-		# Just check, commit fails when files fail astyle check
-		check_ret=`astyle --dry-run --style=linux -p -xg -H -U -k3 -j -T4 -m0 -Y -M120 -Q -I $check_files`
-		if [[ $check_ret != '' ]]; then
-			echo $check_ret | sed 's/Formatted /\n/g'
-			echo 'Bluetooth coding style check FAIL! Please modify and commit again!'
-			exit 1
+		bt_filtered_files=()
+		for f in $check_files
+		do
+			if [ -L "$f" ]; then 
+				#ignore link file
+				continue
+			fi
+			bt_filtered_files+=("$f")
+		done
+		if [ -n "$bt_filtered_files" ]; then
+			# Just check, commit fails when files fail astyle check
+			check_ret=`astyle --dry-run --style=linux -p -xg -H -U -k3 -j -T4 -m0 -Y -M120 -Q -I "${bt_filtered_files[@]}"`
+			if [[ $check_ret != '' ]]; then
+				echo $check_ret | sed 's/Formatted /\n/g'
+				echo 'Bluetooth coding style check FAIL! Please modify and commit again!'
+				exit 1
+			fi
+			# Modify max code length and line end style '-xC160 -xL -z2 -c'
+			astyle --style=linux -p -xg -H -U -k3 -j -T4 -m0 -Y -M120 -xC160 -xL -z2 -c -n -q  "${bt_filtered_files[@]}"
+			git add "${bt_filtered_files[@]}"
 		fi
-		# Modify max code length and line end style '-xC160 -xL -z2 -c'
-		astyle --style=linux -p -xg -H -U -k3 -j -T4 -m0 -Y -M120 -xC160 -xL -z2 -c -n -q $check_files
-		git add $check_files
 	fi
 fi
 
